### ISSUE TITLE
google oauth2 token endpoint constants change

### ISSUE THREAD

**Issue by gdasher** [golang/oauth2#344] opened 2018-11-07 17:09 UTC
Google is migrating the OAuth2 token endpoint from https://accounts.google.com/o/oauth2/token
to https://oauth2.googleapis.com/token.  golang oauth2 library needs to be updated as part of this.  

It appears, from glancing at the code, that it honors the token endpoint specified in the client JSON configuration, which means that the change here is mostly cleanup for clients without explicitly specified token endpoints and is thus less urgent (should be verified by library owner).

The primary urgency is that some features of GCP that are used by a number of GCP customers (most urgently VPC service controls which is one of, maybe the, top revenue unblocking feature across GCP at this point) only work on the new token endpoint because of how they interact with private API access to GCP.

The change has already been deployed in most Google oauth2 libraries for a number of months and no issues have been found.  Functionally, the behavior is nearly identical.   In more detail, the requested changes are as follows:

OAuth 2.0 Authorization Grant Flow (aka 3LO)

For clients using this flow, change (and test):
https://accounts.google.com/o/oauth2/token -> https://oauth2.googleapis.com/token
https://accounts.google.com/o/oauth2/revoke -> https://oauth2.googleapis.com/revoke
https://accounts.google.com/o/oauth2/tokeninfo -> https://oauth2.googleapis.com/tokeninfo
DO NOT change https://accounts.google.com/o/oauth2/auth

If the client pulls the data from the client json object, that will be updated on the server side for newly created clients and no changes to the client libraries are required.

OAuth 2.0 Assertion Flow (aka OAuth 2.0 Service Account Flow, aka “Google Credentials Auth”)

For clients using these flows, change:
https://accounts.google.com/o/oauth2/token -> https://oauth2.googleapis.com/token
The “audience” of the token from https://accounts.google.com/o/oauth2/token ->  https://oauth2.googleapis.com/token

JWT Bearer

No changes should be required for JWT Bearer authentication

ODIC Identity Tokens [Does not seem to be supported in GoLang]

There are two options.  If possible, the preferred option in this case is to:
Change https://accounts.google.com/o/oauth2/token ->  https://oauth2.googleapis.com/token
Change audience verification from “accounts.google.com” to [“accounts.google.com”, “https://accounts.google.com”]
DO NOT Change https://www.googleapis.com/oauth2/v1/certs

If this is too risky in a particular client library, then the change should be:
https://accounts.google.com/o/oauth2/token -> https://www.googleapis.com/oauth2/v3/token
DO NOT Change https://www.googleapis.com/oauth2/v1/certs

**Comment by drebes** [comment] 2019-06-10 11:30
This looks like a dupe of golang/oauth2#310 which has already been fixed. Can you confirm and close this if so?

**Closed** 2019-06-10 16:47 UTC
