### ISSUE TITLE
oauth2 issue with appengine

### ISSUE THREAD

**Issue by terrywarwar** [golang/oauth2#72] opened 2014-12-22 01:31 UTC
appengine storage example on https://cloud.google.com/appengine/docs/go/googlecloudstorageclient/getstarted uses the following code:

opts, err := oauth2.New(
                google.AppEngineContext(c),
                oauth2.Scope(storage.ScopeFullControl),
        )

I get the following errors:
server.go:87: undefined: oauth2.New
server.go:88: undefined: google.AppEngineContext
server.go:89: undefined: oauth2.Scope

**Comment by eboudrant** [comment] 2015-01-02 17:43
@derekperkins @adg The Go version problem is for this error : 
unknown net.Dialer field 'KeepAlive' in struct literal

What about :
server.go:87: undefined: oauth2.New
server.go:88: undefined: google.AppEngineContext
server.go:89: undefined: oauth2.Scope

Can we expect a fix soon ? I use go1.4beta on appengine.

**Comment by rakyll** [comment] 2015-01-02 19:50
> What about :
server.go:87: undefined: oauth2.New

We have modified the API. See http://godoc.org/golang.org/x/oauth2/google#example-AppEngineTokenSource and modify your code accordingly.

Duplicate of https://github.com/golang/oauth2/issues/70.

**Closed by rakyll** 2015-01-02 19:50 UTC
