### ISSUE TITLE
0-legged Oauth Supporting ?

### ISSUE THREAD

**Issue by wenruij** [golang/oauth2#170] opened 2016-01-26 08:25 UTC
Hi,
Just wondering is it possible to do an 0-legged Oauth by your `oauth2`?
saying i just get an API key / secret as the consumer key, without any token, is it possible to get the signed url with your `oauth2`?

**Comment by adg** [comment] 2016-01-27 05:41
Is that even OAuth2? It doesn't sound like it.

**Comment by pvdvreede** [comment] 2017-10-19 01:52
Is this referring to the implicit grant? where the response_type is set to token or id_token and the redirect contains the token or id_token rather than an auth code? eg: https://auth0.com/docs/api-auth/tutorials/implicit-grant

It seems as though the response_type is hardcoded to `code` so doesnt allow this flow at the moment...

**Comment by zombiezen** [comment] 2018-01-03 00:01
Triaging: if this is implicit grant, then it's a dupe of #138.  Otherwise, this might be referring to client credentials, which is supported.  Either way, closing.

**Closed by zombiezen** 2018-01-03 00:01 UTC
